/*
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.ide;


/**
 * Use this class to register ide components.
 */
public class LlmsIdeModule extends AbstractLlmsIdeModule {
}
