/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bodies</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Bodies#getVar <em>Var</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Bodies#getLoops <em>Loops</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Bodies#getCond <em>Cond</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getBodies()
 * @model
 * @generated
 */
public interface Bodies extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.GenericVariable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getBodies_Var()
   * @model containment="true"
   * @generated
   */
  EList<GenericVariable> getVar();

  /**
   * Returns the value of the '<em><b>Loops</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Loops}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loops</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getBodies_Loops()
   * @model containment="true"
   * @generated
   */
  EList<Loops> getLoops();

  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Conditionals}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getBodies_Cond()
   * @model containment="true"
   * @generated
   */
  EList<Conditionals> getCond();

} // Bodies
