/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.BooleanFunction#getPrimary <em>Primary</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getBooleanFunction()
 * @model
 * @generated
 */
public interface BooleanFunction extends Operation
{
  /**
   * Returns the value of the '<em><b>Primary</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Primary}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getBooleanFunction_Primary()
   * @model containment="true"
   * @generated
   */
  EList<Primary> getPrimary();

} // BooleanFunction
