/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.CallVariable#getVars <em>Vars</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getCallVariable()
 * @model
 * @generated
 */
public interface CallVariable extends ParmsPrint
{
  /**
   * Returns the value of the '<em><b>Vars</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' reference.
   * @see #setVars(Variables)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getCallVariable_Vars()
   * @model
   * @generated
   */
  Variables getVars();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.CallVariable#getVars <em>Vars</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vars</em>' reference.
   * @see #getVars()
   * @generated
   */
  void setVars(Variables value);

} // CallVariable
