/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Doubles</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Doubles#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getDoubles()
 * @model
 * @generated
 */
public interface Doubles extends Data
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getDoubles_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Doubles#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Doubles
