/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Functions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Functions#getOutput <em>Output</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Functions#getName <em>Name</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Functions#getParams <em>Params</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Functions#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getFunctions()
 * @model
 * @generated
 */
public interface Functions extends EObject
{
  /**
   * Returns the value of the '<em><b>Output</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Output</em>' containment reference.
   * @see #setOutput(ParametersOutptut)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getFunctions_Output()
   * @model containment="true"
   * @generated
   */
  ParametersOutptut getOutput();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Functions#getOutput <em>Output</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Output</em>' containment reference.
   * @see #getOutput()
   * @generated
   */
  void setOutput(ParametersOutptut value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(Names)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getFunctions_Name()
   * @model containment="true"
   * @generated
   */
  Names getName();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Functions#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(Names value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference.
   * @see #setParams(Parametersfunc)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getFunctions_Params()
   * @model containment="true"
   * @generated
   */
  Parametersfunc getParams();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Functions#getParams <em>Params</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Params</em>' containment reference.
   * @see #getParams()
   * @generated
   */
  void setParams(Parametersfunc value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Bodies)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getFunctions_Body()
   * @model containment="true"
   * @generated
   */
  Bodies getBody();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Functions#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Bodies value);

} // Functions
