/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generic Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getGenericVariable()
 * @model
 * @generated
 */
public interface GenericVariable extends EObject
{
} // GenericVariable
