/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.LogicalOperation#getBoolFunc <em>Bool Func</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.LogicalOperation#getLgicOp <em>Lgic Op</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.LogicalOperation#getLeft <em>Left</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.LogicalOperation#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLogicalOperation()
 * @model
 * @generated
 */
public interface LogicalOperation extends LogicalParams, Operation
{
  /**
   * Returns the value of the '<em><b>Bool Func</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.BooleanFunction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Func</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLogicalOperation_BoolFunc()
   * @model containment="true"
   * @generated
   */
  EList<BooleanFunction> getBoolFunc();

  /**
   * Returns the value of the '<em><b>Lgic Op</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.LogicalOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lgic Op</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLogicalOperation_LgicOp()
   * @model containment="true"
   * @generated
   */
  EList<LogicalOperation> getLgicOp();

  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Primary)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLogicalOperation_Left()
   * @model containment="true"
   * @generated
   */
  Primary getLeft();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.LogicalOperation#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Primary value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Primary)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLogicalOperation_Right()
   * @model containment="true"
   * @generated
   */
  Primary getRight();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.LogicalOperation#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Primary value);

} // LogicalOperation
