/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loops</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Loops#getVar <em>Var</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Loops#getNumber <em>Number</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Loops#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLoops()
 * @model
 * @generated
 */
public interface Loops extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(GenericVariable)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLoops_Var()
   * @model containment="true"
   * @generated
   */
  GenericVariable getVar();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Loops#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(GenericVariable value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' containment reference.
   * @see #setNumber(Numbers)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLoops_Number()
   * @model containment="true"
   * @generated
   */
  Numbers getNumber();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Loops#getNumber <em>Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' containment reference.
   * @see #getNumber()
   * @generated
   */
  void setNumber(Numbers value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Bodies}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getLoops_Body()
   * @model containment="true"
   * @generated
   */
  EList<Bodies> getBody();

} // Loops
