/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Operations#getName <em>Name</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Operations#getFunc <em>Func</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Operations#getVars <em>Vars</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Operations#getConditional <em>Conditional</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Operations#getLoops <em>Loops</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Operations#getPrint <em>Print</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOperations()
 * @model
 * @generated
 */
public interface Operations extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOperations_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Operations#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Func</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Functions}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOperations_Func()
   * @model containment="true"
   * @generated
   */
  EList<Functions> getFunc();

  /**
   * Returns the value of the '<em><b>Vars</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.varParmArgs}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOperations_Vars()
   * @model containment="true"
   * @generated
   */
  EList<varParmArgs> getVars();

  /**
   * Returns the value of the '<em><b>Conditional</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Conditionals}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditional</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOperations_Conditional()
   * @model containment="true"
   * @generated
   */
  EList<Conditionals> getConditional();

  /**
   * Returns the value of the '<em><b>Loops</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Loops}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loops</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOperations_Loops()
   * @model containment="true"
   * @generated
   */
  EList<Loops> getLoops();

  /**
   * Returns the value of the '<em><b>Print</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.Prints}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Print</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOperations_Print()
   * @model containment="true"
   * @generated
   */
  EList<Prints> getPrint();

} // Operations
