/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ors</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getOrs()
 * @model
 * @generated
 */
public interface Ors extends BooleanFunction
{
} // Ors
