/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameters Outptut</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.ParametersOutptut#getParam <em>Param</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.ParametersOutptut#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getParametersOutptut()
 * @model
 * @generated
 */
public interface ParametersOutptut extends EObject
{
  /**
   * Returns the value of the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' containment reference.
   * @see #setParam(varParmArgs)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getParametersOutptut_Param()
   * @model containment="true"
   * @generated
   */
  varParmArgs getParam();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.ParametersOutptut#getParam <em>Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' containment reference.
   * @see #getParam()
   * @generated
   */
  void setParam(varParmArgs value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link large.logic.forMathematics.statistics.llms.varParmArgs}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getParametersOutptut_Params()
   * @model containment="true"
   * @generated
   */
  EList<varParmArgs> getParams();

} // ParametersOutptut
