/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Variables#getTypesVars <em>Types Vars</em>}</li>
 *   <li>{@link large.logic.forMathematics.statistics.llms.Variables#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getVariables()
 * @model
 * @generated
 */
public interface Variables extends Loops
{
  /**
   * Returns the value of the '<em><b>Types Vars</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types Vars</em>' containment reference.
   * @see #setTypesVars(EObject)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getVariables_TypesVars()
   * @model containment="true"
   * @generated
   */
  EObject getTypesVars();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Variables#getTypesVars <em>Types Vars</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Types Vars</em>' containment reference.
   * @see #getTypesVars()
   * @generated
   */
  void setTypesVars(EObject value);

  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(Expression)
   * @see large.logic.forMathematics.statistics.llms.LlmsPackage#getVariables_Exp()
   * @model containment="true"
   * @generated
   */
  Expression getExp();

  /**
   * Sets the value of the '{@link large.logic.forMathematics.statistics.llms.Variables#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(Expression value);

} // Variables
