/*
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractLlmsValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(large.logic.forMathematics.statistics.llms.LlmsPackage.eINSTANCE);
		return result;
	}
}
