/**
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.llms.impl;

import large.logic.forMathematics.statistics.llms.GreaterOrEqual;
import large.logic.forMathematics.statistics.llms.LlmsPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Greater Or Equal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GreaterOrEqualImpl extends LogicalOperationImpl implements GreaterOrEqual
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GreaterOrEqualImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LlmsPackage.Literals.GREATER_OR_EQUAL;
  }

} //GreaterOrEqualImpl
