/*
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.ui;

import com.google.inject.Injector;
import large.logic.forMathematics.statistics.ui.internal.StatisticsActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LlmsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(StatisticsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		StatisticsActivator activator = StatisticsActivator.getInstance();
		return activator != null ? activator.getInjector(StatisticsActivator.LARGE_LOGIC_FORMATHEMATICS_STATISTICS_LLMS) : null;
	}

}
