/*
 * generated by Xtext 2.35.0
 */
package large.logic.forMathematics.statistics.ui.tests;

import com.google.inject.Injector;
import large.logic.forMathematics.statistics.ui.internal.StatisticsActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LlmsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatisticsActivator.getInstance().getInjector("large.logic.forMathematics.statistics.Llms");
	}

}
